# SwiftLint Configuration
# See: https://github.com/realm/SwiftLint

# Paths to lint
included:
  - MyFirstiOSApp

# Paths to exclude
excluded:
  - MyFirstiOSApp/Resources

# Rules
disabled_rules:
  - trailing_whitespace
  - line_length
  - function_body_length
  - file_length
  - type_body_length

opt_in_rules:
  - empty_count
  - closure_spacing
  - force_unwrapping
  - implicitly_unwrapped_optional
