/// GenerableEvent.swift
/// ====================
/// Structured output types for Apple Foundation Models event extraction.
///
/// ## What This Does
/// These types define the schema that the on-device Foundation Models LLM uses
/// to produce structured output. The `@Generable` macro tells the framework
/// to constrain the model's output to match these types exactly, eliminating
/// the need to parse free-form text.
///
/// ## Why Separate from ExtractedEvent?
/// `ExtractedEvent` has `let id = UUID()` which auto-generates a unique ID.
/// The `@Generable` macro requires all properties to be directly settable by
/// the model — it cannot generate UUIDs. So we use these intermediate types
/// for model output, then convert to `ExtractedEvent` after generation.
///
/// ## How @Generable Works
/// The `@Generable` macro (from the `FoundationModels` framework) inspects the
/// struct's properties and generates a JSON schema that the on-device model must
/// follow. The `@Guide` property wrapper adds natural-language descriptions to
/// help the model understand what each field should contain.

#if canImport(FoundationModels)

import Foundation
import FoundationModels

/// A single event as generated by the Foundation Models LLM.
/// Mirrors `ExtractedEvent` but without the auto-generated UUID.
@available(iOS 26.0, *)
@Generable
struct GenerableEvent {
    @Guide(description: "Start date/time. Use 'YYYY-MM-DD HH:mm' for events with specific times (e.g. '2026-03-13 19:00'), or 'YYYY-MM-DD' for date-only multi-day events (e.g. '2026-05-14').")
    var datetimeStart: String

    @Guide(description: "End date/time in the same format as datetimeStart, or nil if no end time is specified. When an event ends at midnight, use the NEXT calendar day at '00:00' (e.g. event on March 13 ending at midnight = '2026-03-14 00:00').")
    var datetimeEnd: String?

    @Guide(description: "Short event title with key performers or hosts. Do NOT include dates, times, prices, or addresses.")
    var description: String
}

/// The top-level container for Foundation Models structured output.
/// Contains an array of extracted events in chronological order.
@available(iOS 26.0, *)
@Generable
struct GenerableEventList {
    @Guide(description: "Array of extracted events in chronological order by start time. Empty array if no future events are found in the input.")
    var events: [GenerableEvent]
}

#endif
